### ISSUE TITLE
Android Exposure Notifications API Link Not Working

### ISSUE THREAD

**Issue by mattgraham1** [google/exposure-notifications-android#15]
Android Exposure Notifications API Link to API doc is not working on the main page.

https://static.googleusercontent.com/media/www.google.com/en//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.1.pdf

**Comment by Apisov** [comment]
There is new version already
https://static.googleusercontent.com/media/www.google.com/en//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.2.pdf

But the "safest" way to track the progress is to follow this link
https://www.google.com/covid19/exposurenotifications/

**Comment by mattgraham1** [comment]
Cool, the main page link is now working. I'll close this out!

**Comment by mirh** [comment]
Ehrm.. why's the advertised spec there 1.2.2 now?
