### ISSUE TITLE
Interop testing of COVID-19 contact tracing 

### ISSUE THREAD

**Issue by olafland** [google/exposure-notifications-android#20]
We are a university research group working on providing your bluetooth based COVID-19 contact tracing on simple BLE wristbands (as open source project). Our aim is to enable inclusive Covid contact tracing. Many young children, elderly persons, persons with disabilities and also persons with low income all over the world do not have a smartphone or cannot operate it. 

Our technical key goal is to provide full compatibility with your COVID-19 contact tracing while using simple, cheap BLE wristbands (10 USD level). This is ongoing work, and some open challenges and tasks remain, but we are confident this can work out. However, we do not want to use the official contact app for interoperability testing. I want to (1) avoid that our test packets end up in the official database and (2) the actual release date for many countries is still some weeks ahead. Do you have a testing framework or traces? According to the document Exposure Notification - Cryptography Specification test vectors should be available. I have seen this code base and also the server example, but I was looking for actual BLE packets, unit tests, or similar. 

Unsure if this is a good place to ask this. If not, I will happy if you could refer me on.

**Comment by seventhmoon** [comment]
https://blog.google/documents/70/Exposure_Notification_-_Bluetooth_Specification_v1.2.2.pdf

**Comment by olafland** [comment]
Thanks, for the links. This information has been available for a while and we already used these specs to implement our code. My question was about actual testing. I want to make sure that we implemented the specs correctly and the BLE packets we send out are correctly received and handled by Android and iOS phones. And the we handle the packets from Android and iOS phones correctly. I would like to find a way to test the full stack from low-level packet format up to crypto. Moreover, I want to avoid using the official COVID-19 contact tracing apps for interoperability testing, as our test packets should not end up in any exposure data bases.

**Comment by pinkit-cwa** [comment]
I would like to emphasize that the [Cryptography Specification](https://blog.google/documents/69/Exposure_Notification_-_Cryptography_Specification_v1.2.1.pdf) states:

> Test Vectors
> Test vectors for interoperability testing between implementations of this specification are available
> upon request in a machine-readable format.

I think this is exactly what @olafland is requesting. Sadly the document does not tell how to perform this request.

**Comment by nic0lette** [comment]
> I would like to emphasize that the [Cryptography Specification](https://blog.google/documents/69/Exposure_Notification_-_Cryptography_Specification_v1.2.1.pdf) states:
> 
> > Test Vectors
> > Test vectors for interoperability testing between implementations of this specification are available
> > upon request in a machine-readable format.
> 
> I think this is exactly what @olafland is requesting. Sadly the document does not tell how to perform this request.

The test vectors are [available here](https://github.com/google/exposure-notifications-internals/blob/abb51a5f06afc1917edba22abaf476492a85bfde/app/src/androidTest/java/com/google/samples/exposurenotification/testing/TestVectors.java)
