### ISSUE TITLE
Dead link 'Exposure Key Export and File Format' on README.md

### ISSUE THREAD

**Issue by taisukef** [google/exposure-notifications-android#32]
can't access this link on links at README.md
https://static.googleusercontent.com/media/www.google.com/en//covid19/exposurenotifications/pdfs/Exposure-Key-File-Format-and-Verification.pdf

can't search it also

**Comment by gurayAlsac** [comment]
That resource is now at
https://developers.google.com/android/exposure-notifications/exposure-key-file-format

You might need to sync to pick up
https://github.com/google/exposure-notifications-server/pull/612

**Comment by taisukef** [comment]
Thank you!
