### ISSUE TITLE
Suggested consistent wording in API and open source project docs

### ISSUE THREAD

**Issue by jixiangox** [google/exposure-notifications-android#34]
https://static.googleusercontent.com/media/www.google.com/en//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.2.pdf

[Temporary Exposure Keys] | {Diagnosis Keys}

 [medical provider] | {PHA}

 [polling] | {fetching}

Mobile app

Your app does the following:
● Provides [Temporary Exposure Keys] | {Diagnosis Keys}, key start time number, and key transmission risk level from your internet-accessible server to Google Play services.
   Information subject to copyright. All rights reserved. Version 1.3.2

 ● Retrieves keys from the on-device data store and submits them to your internet-accessible server after a user has been confirmed by a [medical provider] | {PHA} as having tested positive

● Schedules [polling] | {fetching} of your internet-accessible server for keys.

**Comment by nic0lette** [comment]
Thank you for the suggested updates.

> [Temporary Exposure Keys] | {Diagnosis Keys}

These two terms are not interchangeable. A "Temporary Exposure Key" is used to derive the IDs that are broadcast. A "Diagnosis Key" is a "Temporary Exposure Key" that was downloaded from a server that was confirmed to have tested COVID-19 positive.

>  Retrieves keys from the on-device data store and submits them to your internet-accessible server after a user has been confirmed by a [medical provider] | {PHA} as having tested positive

A Public Health Authority may not confirm tests, however. It is more likely that a doctor, hospital, or lab would confirm the results of a test.

> Schedules [polling] | {fetching} of your internet-accessible server for keys.

I've passed this along to the rest of the team. :)

**Comment by jixiangox** [comment]
My points here are to height both Google Play Service and Mobile App do the same thing, generate TEK, in EN API doc.

**Comment by jixiangox** [comment]
It has been resolved, updated, and clarified in [v1.5](https://developers.google.com/android/exposure-notifications/exposure-notifications-api)
