### ISSUE TITLE
Wrong status bar notifications from Google exposure framework

### ISSUE THREAD

**Issue by aurisnoctis** [google/exposure-notifications-android#35]
**Describe the bug**
When either location or bluetooth is not switched on, the Google exposure notification framework pushes notifications to the Android status bar. These notifications, however, are sometimes incorrect, i.e. not reliable.

**To Reproduce**
1. Use a stock Android version 6.0.1 on a Samsung S5, patched as far as provided by Samsung.
2. Make sure in `Android Settings` > `Google` that exposure notifications are active (yes).
3. Make sure in `Android Settings` > `Apps` that Google Play Services are allowed to push notifications (yes).
4. Switch on and off location and bluetooth randomly and in varying combinations.
5. See that the notifications from the Google exposure framework don't match the current Android settings, see below.

**Expected behavior**
- If `location` is switched off I expect a notification to turn on location to use the exposure framework.
- If `bluetooth` is switched off I expect a notification to turn on bluetooth to use the exposure framework.

**Screenshots**
| | | |
|:-------------------------:|:-------------------------:|:-------------------------:|
|<img width="1604" alt="1-on_int_loc_blue-warn_blue" src="https://user-images.githubusercontent.com/8195964/85415110-37c5e400-b56d-11ea-99af-8cdfcc99f569.png">  Internet, location, **bluetooth on**, but notification from Google COVID-19 framework that **bluetooth is off**. |  <img width="1604" alt="2-Google_OK_warn_active" src="https://user-images.githubusercontent.com/8195964/85415115-38f71100-b56d-11ea-8542-8c0f6b22ca28.png"> Google settings show **no warning** (correct) but **notification about missing bluetooth** is still in status bar. |<img width="1604" alt="3-on_int_loc_blue-warn_loc" src="https://user-images.githubusercontent.com/8195964/85415116-398fa780-b56d-11ea-9191-c8c9bd78c33a.png"> Internet, **location**, bluetooth **on**, but notification from Google framework that **location is off**.|
|<img width="1604" alt="4-on_int_blue-warn_blue" src="https://user-images.githubusercontent.com/8195964/85415119-3a283e00-b56d-11ea-81a6-cb08a4005c66.png"> Internet, **bluetooth on**, but warning from Google framework that **bluetooth is off**. |  <img width="1604" alt="5-on_int_loc-warn_loc" src="https://user-images.githubusercontent.com/8195964/85415121-3ac0d480-b56d-11ea-9a63-d28d1db25467.png"> Internet, **location on**, but warning from Google framework that **location is off** still in status bar. |<img width="1604" alt="6-setting_loc_OK-warn_loc" src="https://user-images.githubusercontent.com/8195964/85415125-3bf20180-b56d-11ea-95f1-c6996df18903.png"> Location settings show: location is **switched on**, but still warning from Google framework in status bar that **location is off**.|

- All of the screenshots above were made after waiting for at least **several minutes** after each change in settings. I see the COVID-19 framework notification about missing location by now for **several hours** even though location is switched on.
- How can users be expected **not to dismiss those misleading notifications?** Not helpful for the cause of dependent apps.

**Device (if relevant):**
 - Device: Samsung S5 (SM-G900F)
 - OS: Android 6.0.1 (stock Android, patched as far as provided by Samsung) in German Language

**Additional context**
Related to issue https://github.com/corona-warn-app/cwa-app-android/issues/491 for the German Corona-Warn-App (CWA): neither Google nor CWA provide reliable warnings when location is switched off.

**Comment by jakobmoellersap** [comment]
These notifications are not influenced by CWA and are a result of the Play Services Notification Set provided with the Exposure Notification API. As such, we can not influence their behavior, look or UX.

**Comment by aurisnoctis** [comment]
@jakobmoellersap That's why I posted it here. **This is the Google repo**.

**Comment by aurisnoctis** [comment]
@jakobmoellersap As there is no feedback here - I heard you are in contact with Google. Could you please make them aware? As the bug described about happens when trying out different combinations of bluetooth and location being switched on and off, it could be a bug in how these different combinations of on/off status are handled.

**Comment by aurisnoctis** [comment]
Seems fixed now.

ENF version 15202902003 on Samsung S5 with stock Android 6.0.1.
