### ISSUE TITLE
Problem rolling out v1.5

### ISSUE THREAD

**Issue by gitbrueck** [google/exposure-notifications-android#42]
Note: This issue tracker is for reporting bugs in the Android Reference Design only. 

**Describe the bug**
 I still have v1.0 of EN API.

**To Reproduce**
Settings>Google>COVID-19 Exposure Notifications>ExposureNotification
Turn Off.
Unable to turn on again!

**Expected behavior**
V1.5 must be installed -> Possibility to turn on Exposure Notification in Settings.

**Device (if relevant):**
 - Model number: F3311
 - Android version: 6.0
 - COVID-19 Notifications Version 202414000

**Additional context**
Using Corona Warn App in Germany

**Comment by pflammertsma** [comment]
Are you able to turn on Exposure Notification from Corona-Warn-App by launching it and giving consent when prompted?

**Comment by gitbrueck** [comment]
> 
> 
> Are you able to turn on Exposure Notification from Corona-Warn-App by launching it and giving consent when prompted?

yes

**Comment by gitbrueck** [comment]
Now, I have v1.5 of this API! 👍
