### ISSUE TITLE
Link to Android-Exposure-Notification-API-documentation-v1.3.2.pdf is broken

### ISSUE THREAD

**Issue by marekaf** [google/exposure-notifications-android#43]
Hello 👋  can somebody take a look at this, please?:) 
**Describe the bug**
README.md is linking to this [resource](https://static.googleusercontent.com/media/www.google.com/en//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.2.pdf) which throws 404

**Comment by jixiangox** [comment]
https://developers.google.com/android/exposure-notifications/exposure-notifications-api

**Comment by jpromnam** [comment]
_

**Comment by MikeMcC399** [comment]
It seems that this issue has already been fixed in
https://github.com/google/exposure-notifications-android/blob/master/README.md

**Comment by nic0lette** [comment]
Yup. Thanks!
