### ISSUE TITLE
Provide better error during onboarding if EN Play Services module is not installed

### ISSUE THREAD

**Issue by voluphixmediaz** [google/exposure-notifications-android#5]
Turn on notifications always shows "Internal error, please try again" please help on how to approach it, what is the cause and how to fix it thanks a lot .

**Comment by ayoubphy** [comment]
You need access to the APIs, access is granted only if you're authorized by your country's health authorities to build the app, furthermore, your country needs to contact google and apple directly to request access.

**Comment by cpepi001** [comment]
Do we know if any country/state has started the implementation of these APIs?

**Comment by ayoubphy** [comment]
> Do we know if any country/state has started the implementation of these APIs?

No we don't. I am think they way google and apple have handled this entire rollout could be better. All information they gave is vague and incomplete.

**Comment by simonroesch** [comment]
The DP3T project started integrating the GAEN framework already. This is still work in progress, but you can checkout https://github.com/DP-3T/dp3t-sdk-android/tree/gaen for the current state of the Android DP3T SDK. The code of the proximity app of Switzerland is also available on https://github.com/DP-3T/dp3t-app-android-ch and will use the new DP3T SDK with GAEN support as soon as possible.

**Comment by tjohns** [comment]
Thanks for the report.

You're getting this error because your phone doesn't have the Exposure Notifications module for Play Services installed. A pre-release build of this module is currently available to public health agencies for development purposes, but is not yet available publicly.

We'll be updating the error messaging during the onboarding flow to clarify this as part of a future update.

**Comment by voluphixmediaz** [comment]
> You need access to the APIs, access is granted only if you're authorized by your country's health authorities to build the app, furthermore, your country needs to contact google and apple directly to request access.

How do i get in touch with google i am communicating with the Ministry of Health but how do i send them a letter or form Ministry will have to fill so that google can grant permission thank you so much.
