### ISSUE TITLE
File Format?

### ISSUE THREAD

**Issue by Redth** [google/exposure-notifications-android#6]
Can we get more information on the file format expected?  Is it going to use the same protobuf spec as Apple?

We are trying to enable our customers to use this SDK in their Xamarin apps and there are a number of questions such as the file format that we have and no point of contact to help answer them.  Any help is appreciated!

**Comment by tjohns** [comment]
Documentation regarding the Exposure Key File Format is still under revision and hasn't been publicly released yet.

If you are working on behalf of a public health agency, you should have already had someone from Google reach out to you to help answer questions. If not, please make sure a representative from your public health agency has completed the advance notice form here:

https://support.google.com/googleplay/android-developer/contact/expo_notif_api

**This form should be completed only by representatives of government public health agencies.**
