### ISSUE TITLE
Improving proximity estimation by handling RSSI per advertisement channel

### ISSUE THREAD

**Issue by elanfer** [google/exposure-notifications-android#61]
Hi, I am not sure if I understood the documentation of the API right, so I wanted to ask: Is it correct that in android version > 9, exposure notifications are received on all three BTLE advertisement channels, 37, 38 and 39, and then the RSSI values received on that channels will be averaged and stored into the ScanInstance structure? Will these averaged values then be used to compute the attenuation value that is used as a distance estimator (https://developers.google.com/android/exposure-notifications/ble-attenuation-overview)? 

I am asking, because on behalf of my master thesis, I measured RSSI values in BTLE for different distance channel wise. And these measurements have shown that there are big differences in RSSI between these channels. Here are some of my results for an (almost empty) office environment:
![ble_single_channels](https://user-images.githubusercontent.com/6481985/101282233-3105f300-37d4-11eb-9577-4a16278179db.png)

I am concerned now, that if we average those values over the three channels, we will generate a less accurate RSSI value for the attenuation calculation than the situation really is. In a way, that a close contact, was for example correctly detected with a high RSSI value greater than -45dBm on channel 37 and then by averaging with the other received values like a -60 on channel 38 and 39, the indicator will be lower than -55 and a false negative will be produced. And as we already know (e.g. from [Leith and Farrell](https://www.scss.tcd.ie/Doug.Leith/pubs/luas.pdf)), using RSSI as a distance approximation is very error prone, already if we only use one channel. But we could take advantage of the presence of all three channels. My suggestion in this case would be, only using the channel where the maximum RSSI value was received out of the three channels. As I don't know if the channel can be determined (Edit: I know read a paper and detailed parts in the standard, that the channel information ist not available. [Gentner, Günther and Kindt are suggesting an approach to retreive channel information](https://arxiv.org/abs/2006.09099)), another solution would be to use the maximum RSSI for a specific time window. This then could be a more close to reality description with better signal propagation characteristics, which hopefully results in less false negative results. 

I hope my suggestion can help to improve the distance estimation (if it isn't already implemented in a way without averaging) :) 

best regards,
Eric

**Comment by nic0lette** [comment]
Hi @elanfer ,

Thank you for sharing your analysis and the suggestion. In fact, your suggestion is already supported. If you look at [`ScanInstance`](https://github.com/google/exposure-notifications-internals/blob/7dadb83aa5c4b02ed4ae98cd8cf13f89b96962d2/exposurenotification/src/main/java/com/google/samples/exposurenotification/nearby/ScanInstance.java), which is part of an [`ExposureWindow`](https://github.com/google/exposure-notifications-internals/blob/7dadb83aa5c4b02ed4ae98cd8cf13f89b96962d2/exposurenotification/src/main/java/com/google/samples/exposurenotification/nearby/ExposureWindow.java), there's a field called [`minAttenuationDb`](https://github.com/google/exposure-notifications-internals/blob/7dadb83aa5c4b02ed4ae98cd8cf13f89b96962d2/exposurenotification/src/main/java/com/google/samples/exposurenotification/nearby/ScanInstance.java#L50-L55) which has the maximum RSSI value seen.

Thank you again for reaching out and best of luck with your research!

**Comment by elanfer** [comment]
Hi @nic0lette 

Thanks a lot for your reply! I've also seen the field minAttenuationDb, but I haven't found any further usage of it, not in the android app reference implementation, neither in the internals repository. Could you tell me which value is used to compute the distance factor, that is later used to calculate the risk? In most places where I assumed that it is used and calculated, like in the [getDistanceEstimate()](https://github.com/google/exposure-notifications-internals/blob/aa75f5c834aacdcad2aa29d899ba882295b31d16/exposurenotification/src/main/java/com/google/samples/exposurenotification/nearby/DailySummariesConfig.java#L245), only the typicalAttenuationDb is used. 

Thank you!
