### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by lucamtudor** [google/exposure-notifications-android#7]
this made my day. impostor syndrome got a little easier today. just a little, but I'll take the win.
😂

**Comment by tjohns** [comment]
Please try to keep issues constructive.

If you have specific bugs or enhancement requests, I'd be happy to pass them on to the development team.

Also please be aware that, at this time, our team is busy prioritizing engagements with governments and public health authorities to use the new APIs. This repository is provided for transparency, but most development and discussion surrounding this API are not occurring in this repository.
